server:
  port: 8081
  servlet:
    context-path: /asset
    jsp:
       init-parameters:
        development: true
#spring
spring:
  mvc:
    view:
     prefix: /WEB-INF/page/
     suffix: .jsp
mybatis: 
  mapperLocations: classpath:mybatis/com/ossjk/asset/*/mapper/xml/*.xml
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mybatis/com/ossjk/asset/*/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ossjk.asset.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #自定义填充策略接口实现
    meta-object-handler: com.ossjk.asset.common.mybatis.CommonMetaObjectHandler